apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ include "b2-share-broker.namespace" . }}
  labels:
    {{- include "b2-share-broker.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "b2-share-broker.shortName" . }}-processor
  namespace: {{ include "b2-share-broker.namespace" . }}
  labels:
    {{- include "b2-share-broker.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: processor
