apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: b2-share-broker-pg-drain
  namespace: b2-share-broker
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: b2-share-broker-pg
