apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: b2-share-staging
  namespace: b2-share-broker
  labels:
    app.kubernetes.io/name: b2-share-broker
    app.kubernetes.io/component: processor
spec:
  accessModes:
    - ReadWriteOnce
  # Replace with a storage class available in your cluster.
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
